version: "3"

services:
  chrome:
    image: selenium/standalone-chrome
    restart: always
    ports:
      - "4443:4443"
      - "4442:4442"
      - "4444:4444"
    shm_size: '1gb'

  scrapper:
    build:
      context: .
    restart: always
    links:
      - db
    volumes:
      - /api
    ports:
      - "5000:5000"

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - scrapper
      ports:
        - "6127:6127"

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app.celery worker -l info
    # command:  ['celery', '-A', 'app.tasks', 'worker']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    links:
      - redis
    depends_on:
      - redis
      - scrapper   
      - chrome   

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql


volumes:
  my-db:
