version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    restart: always
    privileged: true
    ports:
      - "4443:4443"
      - "4442:4442"
      - "4444:4444"
    shm_size: '2gb'

  scrapper:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
 

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - redis
      ports:
        - "6127:6127"

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app.celery worker -l info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    links:
      - redis
    depends_on:
      - redis
